
stages:
  - build
  - test
  - review
  - stage
  - production

build_job:
  stage: build
  image: docker:19.03.8
  variables:
    DOCKER_TLS_CERTDIR: ''
  services:
    - name: docker:19.03.8-dind
      alias: docker
  before_script:
    - docker info
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
    - docker image ls
  script:
    - echo 'Building'
    - docker build -t ${DOCKER_HUB_LOGIN}/otus-reddit:${CI_COMMIT_TAG:-1.0.0}.${CI_COMMIT_SHORT_SHA:-0} ./reddit
    - docker push ${DOCKER_HUB_LOGIN}/otus-reddit:${CI_COMMIT_TAG:-1.0.0}.${CI_COMMIT_SHORT_SHA:-0}
  after_script:
    - docker image ls

test_unit_job:
  stage: test
  image: ruby:2.4.2
  services:
    - mongo:latest
  variables:
    DATABASE_URL: 'mongo:27017'
  before_script:
    - cd reddit
    - bundle install
  script:
    - echo 'Testing 1'
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  image: docker:19.03.8
  variables:
    DOCKER_TLS_CERTDIR: ''
  services:
    - name: docker:19.03.8-dind
      alias: docker
  before_script:
    - docker info
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
    - apk add curl py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker-compose -f ./reddit/docker-compose.yml config
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
